In [1]:
import numpy as np



In [2]:
#Task1

#Option1

array1d = np.array ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print (array1d)

#Option2

array1D = np.arange(10)
print (array1D)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Task2
#Option 1

my_array = np.array ([1,3,5,7,9,11,13,15,17])
bool_array = my_array > 0
bool_array = bool_array.reshape(3,3)
print (bool_array)

#Option2
my_array = np.array ([1,3,5,7,9,11,13,15,17])
bool_array = my_array == my_array
bool_array = bool_array.reshape(3,3)
print (bool_array)

#Option3
my_array = np.array ([1,3,5,7,9,11,13,15,17])
bool_array = my_array %2 != 0
bool_array = bool_array.reshape(3,3)
print (bool_array)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
#Task3

#Option1
my_array = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for n in my_array:
    if n %2 !=0:
        print (n)

#Option2
my_array = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (my_array[0::2])


   

1
3
5
7
9
[1 3 5 7 9]


In [5]:
#Task4

#Option1
my_array = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_array[my_array%2 !=0] = -1
print(my_array)

#Option2
my_array = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (np.where(my_array % 2 != 0, -1, my_array))



[-1  2 -1  4 -1  6 -1  8 -1 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [6]:
#Task5

my_array = np.arange(10)
print (my_array)

new_array = my_array.reshape (5,2)
print (new_array)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
#Task6

a = np.array([23,44,56,78,80,54, 12, 15, 10]).reshape(3,3)
b = np.array([10,34,22,67,89,21, 22, 4, 42]).reshape(3,3)
c= np.dot(a,b)
print (c)

a = np.array([23,44,56,78]).reshape(2,2)
b = np.array([10,34,22,67]).reshape(2,2)
c= np.dot(a,b)
print (c)
# np.dot only works when number of columns and rows are equal

a = np.array([23,44,56,78,80,54, 12, 15, 10]).reshape(3,3)
b = np.array([10,34,22,67,89,21, 22, 4, 42]).reshape(3,3)
c= np.dot(a,b)
sum = np.sum (c)
print (sum)


[[4410 4922 3782]
 [7328 9988 5664]
 [1345 1783  999]]
[[1198 3730]
 [2276 7130]]
40221


In [8]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c =np.dot(a,b)
e=np.sum(c,axis = 0)
print (e)

a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c =np.dot(a,b)
e=np.sum(c,axis = 1)
print (e)

#Why my results are the other way round than in Power Point presentation?

[603 648 693]
[ 270  648 1026]


In [9]:
#Extension

my_array = np.array([1,2,3,4,5,6,7,8,9,10,4,3,4,5,6,7,8,9])
my_array [0:3] = 1
my_array[3:6]=2
my_array[6:9]=3
my_array[9:18]=1,2,3,1,2,3,1,2,3
#my_array[12:15]
print (my_array)



[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [10]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
if n in a and b ==4 or 5:
    new_b = [6,7,8,9]
    #print (new_b)
else:
    print ([4,5,6,7,8,9])

print (a)
print (new_b)



[1 2 3 4 5]
[6, 7, 8, 9]


In [11]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
new_a = a[2:]
new_b = b[:3]
print (new_a)
print (new_b)
print(new_a + new_b)

#


a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
new_a = a[2:]
new_b = b[:3]
sum = np.dot(new_a, new_b)
print(sum)



[3 4 5]
[4 5 6]
[ 7  9 11]
62
